# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    # - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    tags:
      - cmount
    goos:
      - linux
      #- windows
    goarch:
      - amd64
      #- 386
      - arm64
      #- arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

checksum:
  name_template: 'checksums.txt'
  
snapshot:
  name_template: v1_{{ time "20060102" }}
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
